"""
VulnScan Lite — PDF Report Generation API

Endpoints:
  GET /api/reports/{scan_id}/pdf — generate and download a PDF report

Uses ReportLab to generate a multi-page, executive security report from actual scan data.
Includes NumberedCanvas for dynamic page numbering, detailed tables for SSL/TLS,
Security Headers, CMS detection, HTML metadata, findings, and remediation guides.
"""
import io
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from app.api.auth import get_current_user
from app.database.database import get_db
from app.database.models import Scan, ScanResult, ScanStatus, User

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/reports", tags=["Reports"])

DISCLAIMER = (
    "DISCLAIMER: This report was generated by VulnScan Lite and reflects "
    "passive security analysis only. Only scan websites you own or have "
    "explicit permission to test. VulnScan Lite performs passive security "
    "analysis only and does not perform exploitation, brute force, or any "
    "form of active attack."
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page numbers and footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#94a3b8"))

        # Footer divider
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(2 * cm, 1.5 * cm, 21 * cm - 2 * cm, 1.5 * cm)

        # Left: Branding
        self.drawString(2 * cm, 1.1 * cm, "VulnScan Lite — Passive Security Health Report")

        # Right: Page X of Y
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(21 * cm - 2 * cm, 1.1 * cm, page_text)
        self.restoreState()


def _grade_color(grade: Optional[str]) -> colors.Color:
    mapping = {
        "A": colors.HexColor("#22c55e"),
        "B+": colors.HexColor("#84cc16"),
        "B": colors.HexColor("#a3e635"),
        "C": colors.HexColor("#facc15"),
        "D": colors.HexColor("#f97316"),
        "F": colors.HexColor("#ef4444"),
    }
    return mapping.get(grade or "", colors.HexColor("#64748b"))


from app.services.scoring import calculate_risk_level

ETHICAL_NOTICE = (
    "<b>Notice:</b> Only scan systems you own or have explicit permission to test. "
    "VulnScan Lite performs passive security analysis and does not perform active exploitation or destructive testing."
)

LIMITATIONS_TEXT = (
    "<b>Scan Limitations:</b> VulnScan Lite performs passive external security analysis. "
    "It does not perform active exploitation, fuzzing, brute force attacks, or utilize destructive payloads. "
    "It does not assess authenticated application areas, backend databases, or complex multi-step business logic flaws. "
    "A clean scan indicates that tested baseline controls and headers were observed, but does not guarantee the complete absence of security vulnerabilities."
)


def _build_pdf(scan: Scan, result: Optional[ScanResult]) -> bytes:
    """Build a comprehensive PDF report from scan data and return as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2.2 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ----- Header / Branding -----
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=3,
        alignment=TA_LEFT,
    )
    sub_style = ParagraphStyle(
        "ReportSub",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#64748b"),
        alignment=TA_LEFT,
        spaceAfter=8,
    )
    story.append(Paragraph("VulnScan Lite", title_style))
    story.append(Paragraph("Passive Web Security Posture &amp; Misconfiguration Assessment", sub_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#6366f1"), spaceAfter=10))

    # Ethical Notice Banner
    notice_style = ParagraphStyle(
        "NoticeStyle",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#475569"),
        leading=11,
    )
    story.append(Paragraph(ETHICAL_NOTICE, notice_style))
    story.append(Spacer(1, 0.3 * cm))

    # Styles
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, fontName="Helvetica-Bold", textColor=colors.HexColor("#1e293b"), spaceBefore=8, spaceAfter=4)
    normal = ParagraphStyle("Normal", parent=styles["Normal"], fontSize=8.5, textColor=colors.HexColor("#334155"), leading=12)
    table_cell = ParagraphStyle("TableCell", parent=styles["Normal"], fontSize=8, leading=10.5, textColor=colors.HexColor("#1e293b"))
    table_cell_bold = ParagraphStyle("TableCellBold", parent=styles["Normal"], fontSize=8, fontName="Helvetica-Bold", leading=10.5, textColor=colors.HexColor("#0f172a"))

    # ----- Executive Summary -----
    story.append(Paragraph("1. Executive Summary", h2))

    grade = scan.grade or "N/A"
    score_val = scan.score
    score_str = f"{score_val:.1f} / 100" if score_val is not None else "N/A"
    risk_level = calculate_risk_level(score_val)
    completed = scan.completed_at.strftime("%Y-%m-%d %H:%M:%S UTC") if scan.completed_at else "In Progress"

    duration_str = "N/A"
    if scan.started_at and scan.completed_at:
        duration_str = f"{(scan.completed_at - scan.started_at).total_seconds():.2f}s"

    findings_list = scan.findings or []
    total_findings = len(findings_list)
    crit_count = sum(1 for f in findings_list if f.severity.value == "critical")
    high_count = sum(1 for f in findings_list if f.severity.value == "high")
    med_count = sum(1 for f in findings_list if f.severity.value == "medium")
    low_count = sum(1 for f in findings_list if f.severity.value == "low")
    info_count = sum(1 for f in findings_list if f.severity.value == "info")

    summary_data = [
        [Paragraph("Target URL", table_cell_bold), Paragraph(scan.target_url, table_cell)],
        [Paragraph("Scan Reference ID", table_cell_bold), Paragraph(str(scan.id), table_cell)],
        [Paragraph("Scan Completed", table_cell_bold), Paragraph(completed, table_cell)],
        [Paragraph("Scan Duration", table_cell_bold), Paragraph(duration_str, table_cell)],
        [Paragraph("Security Score", table_cell_bold), Paragraph(f"<b>{score_str}</b>", table_cell)],
        [Paragraph("Risk Level", table_cell_bold), Paragraph(f"<b>{risk_level} (Grade {grade})</b>", table_cell)],
        [Paragraph("Total Findings", table_cell_bold), Paragraph(f"{total_findings} (Critical: {crit_count}, High: {high_count}, Med: {med_count}, Low: {low_count}, Info: {info_count})", table_cell)],
    ]

    summary_table = Table(summary_data, colWidths=[4.5 * cm, 12.5 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(summary_table)

    exec_disc = Paragraph(
        "<i>VulnScan Lite detected security configuration weaknesses through passive external analysis. "
        "A high score reflects baseline configuration health, but does not prove the target is entirely free from vulnerabilities.</i>",
        ParagraphStyle("ExecDisc", parent=styles["Normal"], fontSize=7.5, textColor=colors.HexColor("#64748b"), leading=10, spaceBefore=4)
    )
    story.append(exec_disc)
    story.append(Spacer(1, 0.3 * cm))

    # ----- Security Configuration & HTTP Headers Combined Table -----
    if scan.security_checks:
        story.append(Paragraph("2. Security Configuration &amp; HTTP Headers", h2))
        check_data = [
            [
                Paragraph("Check Name", table_cell_bold),
                Paragraph("Category", table_cell_bold),
                Paragraph("Status", table_cell_bold),
                Paragraph("Severity", table_cell_bold),
                Paragraph("Confidence", table_cell_bold),
                Paragraph("Observed Evidence", table_cell_bold),
            ]
        ]
        for c in scan.security_checks:
            status_color = "#22c55e" if c.status.value == "passed" else ("#facc15" if c.status.value == "warning" else ("#ef4444" if c.status.value == "failed" else "#64748b"))
            status_text = f"<font color='{status_color}'><b>{c.status.value.upper()}</b></font>"

            # Determine severity and confidence
            matched_finding = next((f for f in findings_list if f.check_name.lower() in c.check_name.lower() or c.check_name.lower() in f.check_name.lower()), None)
            sev_label = (matched_finding.severity.value.capitalize() if matched_finding else "—")
            conf_label = ((matched_finding.confidence or "high").capitalize() if matched_finding else "High")
            evidence_text = (matched_finding.evidence if matched_finding and matched_finding.evidence else (c.description or "Observed"))

            check_data.append([
                Paragraph(c.check_name, table_cell),
                Paragraph(c.category, table_cell),
                Paragraph(status_text, table_cell),
                Paragraph(sev_label, table_cell),
                Paragraph(conf_label, table_cell),
                Paragraph(evidence_text[:80] + ("..." if len(evidence_text) > 80 else ""), table_cell),
            ])

        checks_table = Table(check_data, colWidths=[4.0 * cm, 2.2 * cm, 1.8 * cm, 1.8 * cm, 1.8 * cm, 5.4 * cm])
        checks_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("PADDING", (0, 0), (-1, -1), 3.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(checks_table)
        story.append(Spacer(1, 0.3 * cm))

    # ----- SSL/TLS Cryptographic Inspection -----
    story.append(Paragraph("3. SSL / TLS Cryptographic Inspection", h2))
    if result and result.ssl_data and result.ssl_data.get("connection_successful", True):
        ssl = result.ssl_data
        ssl_rows = [
            [Paragraph("HTTPS Support", table_cell_bold), Paragraph("Enabled" if ssl.get("is_https") else "Disabled", table_cell)],
            [Paragraph("Certificate Validity", table_cell_bold), Paragraph("Valid" if ssl.get("certificate_valid") else "Invalid / Verification Failed", table_cell)],
            [Paragraph("TLS Version", table_cell_bold), Paragraph(ssl.get("tls_version") or "TLS information unavailable.", table_cell)],
            [Paragraph("Cipher Suite", table_cell_bold), Paragraph(ssl.get("cipher") or "TLS information unavailable.", table_cell)],
            [Paragraph("Subject", table_cell_bold), Paragraph(ssl.get("subject") or "TLS information unavailable.", table_cell)],
            [Paragraph("Issuer", table_cell_bold), Paragraph(ssl.get("issuer") or "TLS information unavailable.", table_cell)],
            [Paragraph("Certificate Expiry", table_cell_bold), Paragraph(ssl.get("not_after") or "N/A", table_cell)],
            [Paragraph("Days Remaining", table_cell_bold), Paragraph(str(ssl.get("days_until_expiry")) if ssl.get("days_until_expiry") is not None else "N/A", table_cell)],
        ]
        ssl_table = Table(ssl_rows, colWidths=[4.5 * cm, 12.5 * cm])
        ssl_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 3.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(ssl_table)
    else:
        story.append(Paragraph("<i>TLS information unavailable.</i>", normal))
    story.append(Spacer(1, 0.3 * cm))

    # ----- Technology Information (Informational) -----
    story.append(Paragraph("4. Technology Information", h2))
    story.append(Paragraph("<i>Technology fingerprinting is informational and does not by itself indicate a vulnerability.</i>", ParagraphStyle("TechInfoNote", parent=styles["Normal"], fontSize=7.5, textColor=colors.HexColor("#64748b"), spaceAfter=4)))

    tech_rows = []
    if result and result.header_data and result.header_data.get("server"):
        tech_rows.append([Paragraph("Web Server Header", table_cell_bold), Paragraph(result.header_data.get("server"), table_cell)])
    if result and result.header_data and result.header_data.get("x_powered_by"):
        tech_rows.append([Paragraph("X-Powered-By", table_cell_bold), Paragraph(result.header_data.get("x_powered_by"), table_cell)])

    if result and result.cms_data and result.cms_data.get("detected"):
        cms = result.cms_data
        tech_rows.append([Paragraph("CMS Platform", table_cell_bold), Paragraph(cms.get("cms_name", "Detected"), table_cell)])
        if cms.get("version"):
            tech_rows.append([Paragraph("CMS Version", table_cell_bold), Paragraph(cms.get("version"), table_cell)])

    if result and result.html_data:
        html = result.html_data
        if html.get("generator"):
            tech_rows.append([Paragraph("Generator Tag", table_cell_bold), Paragraph(html.get("generator"), table_cell)])
        if html.get("technology_indicators"):
            tech_rows.append([Paragraph("Client Libraries / CDNs", table_cell_bold), Paragraph(", ".join(html.get("technology_indicators", [])), table_cell)])

    if tech_rows:
        tech_table = Table(tech_rows, colWidths=[4.5 * cm, 12.5 * cm])
        tech_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 3.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(tech_table)
    else:
        story.append(Paragraph("<i>No server, CMS, or framework signatures disclosed.</i>", normal))
    story.append(Spacer(1, 0.3 * cm))

    # ----- Findings & Remediation Section -----
    story.append(Paragraph("5. Actionable Security Findings &amp; Remediation", h2))
    if findings_list:
        severity_colors = {
            "critical": "#ef4444",
            "high": "#f97316",
            "medium": "#f59e0b",
            "low": "#3b82f6",
            "info": "#64748b",
        }
        for finding in findings_list:
            sev_color_hex = severity_colors.get(finding.severity.value, "#64748b")
            conf_str = (finding.confidence or "high").capitalize()

            finding_flowables = [
                Paragraph(
                    f'<font color="{sev_color_hex}"><b>[{finding.severity.value.upper()}]</b></font> <b>{finding.check_name}</b> '
                    f'<font color="#64748b" size="7.5">(Confidence: {conf_str})</font>',
                    ParagraphStyle("FindingTitle", parent=styles["Heading3"], fontSize=9.5, spaceAfter=2),
                ),
                Paragraph(f"<b>Description:</b> {finding.description}", normal),
            ]

            if finding.impact:
                finding_flowables.append(
                    Paragraph(f"<b>Why this matters:</b> {finding.impact}", normal)
                )

            if finding.evidence:
                finding_flowables.append(
                    Paragraph(f"<b>Evidence:</b> <code>{finding.evidence}</code>", normal)
                )

            if finding.remediation:
                finding_flowables.append(
                    Paragraph(f"<b>Remediation Guidance:</b> {finding.remediation}", normal)
                )

            finding_flowables.append(Spacer(1, 0.25 * cm))
            story.append(KeepTogether(finding_flowables))
    else:
        story.append(Paragraph("<i>No security findings detected by the implemented passive checks. This indicates that baseline passive checks passed, but does not guarantee the absence of all vulnerabilities.</i>", normal))
        story.append(Spacer(1, 0.3 * cm))

    # ----- Scan Limitations -----
    story.append(Paragraph("6. Scan Limitations", h2))
    story.append(Paragraph(LIMITATIONS_TEXT, notice_style))
    story.append(Spacer(1, 0.4 * cm))

    # ----- Legal Disclaimer Footer -----
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceBefore=5, spaceAfter=5))
    disc_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=7,
        textColor=colors.HexColor("#94a3b8"),
        alignment=TA_CENTER,
        leading=9,
    )
    story.append(Paragraph(DISCLAIMER, disc_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


@router.get("/{scan_id}/pdf")
def download_pdf(
    scan_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate and stream a PDF security report for a completed scan.
    Only the scan owner can download the report.
    """
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scan not found.")

    if scan.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access denied.")

    if scan.status != ScanStatus.COMPLETED:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Scan is not yet complete (status: {scan.status.value}).",
        )

    result = db.query(ScanResult).filter(ScanResult.scan_id == scan_id).first()

    pdf_bytes = _build_pdf(scan, result)

    filename = f"vulnscan-{scan_id[:8]}-report.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
